In [1]:
import pandas as pd

dataset_path = r'C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa'
df = pd.read_parquet(dataset_path + '/domain_users.parquet')
print(df.head())
print(df)

          group username
0  sanfrancisco  mat.sco
1  sanfrancisco  mat.sco
2  sanfrancisco  mat.sco
3  sanfrancisco  mat.sco
4  sanfrancisco  mat.sco
            group        username
0    sanfrancisco         mat.sco
1    sanfrancisco         mat.sco
2    sanfrancisco         mat.sco
3    sanfrancisco         mat.sco
4    sanfrancisco         mat.sco
5    sanfrancisco      flet.lee33
6    sanfrancisco      flet.lee33
7    sanfrancisco  maddi.campbel8
8    sanfrancisco  maddi.campbel8
9    sanfrancisco         ricwood
10   sanfrancisco         ricwood
11   sanfrancisco         ricwood
12   sanfrancisco         ricwood
13  domain admins         mat.sco
14  domain admins   Administrator
15  domain admins          svc_em

In [2]:
import os

for root, dirs, files in os.walk(dataset_path):
    for f in files:
        print(os.path.join(root, f))

C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\domain_users.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\loggedonusers\CRW167SL.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\loggedonusers\PXA949WW.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\loggedonusers\RDL208NS.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\loggedonusers\RDL794WW.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\loggedonusers\UMI895SB.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\useraccounts\CRW167SL.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\useraccounts\PXA949WW.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\useraccounts\RDL208NS.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\useraccounts\RDL794WW.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\useraccounts\UMI895SB.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32drivers\CRW167SL.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32drivers\PXA949WW.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32drivers\RDL208NS.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32drivers\RDL794WW.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32drivers\UMI895SB.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32persistence-fileitems\CRW167SL.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32persistence-fileitems\PXA949WW.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32persistence-fileitems\RDL208NS.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32persistence-fileitems\RDL794WW.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32persistence-fileitems\UMI895SB.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32persistence-registryitems\CRW167SL.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32persistence-registryitems\PXA949WW.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32persistence-registryitems\RDL208NS.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32persistence-registryitems\RDL794WW.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32persistence-registryitems\UMI895SB.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32persistence-servicesitems\CRW167SL.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32persistence-servicesitems\PXA949WW.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32persistence-servicesitems\RDL208NS.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32persistence-servicesitems\RDL794WW.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32persistence-servicesitems\UMI895SB.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32processes\CRW167SL.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32processes\PXA949WW.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32processes\RDL208NS.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32processes\RDL794WW.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32processes\UMI895SB.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32processes-memorysections\CRW167SL.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32processes-memorysections\PXA949WW.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32processes-memorysections\RDL208NS.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32processes-memorysections\RDL794WW.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32processes-memorysections\UMI895SB.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32services\CRW167SL.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32services\PXA949WW.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32services\RDL208NS.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32services\RDL794WW.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32services\UMI895SB.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32tasks\CRW167SL.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32tasks\PXA949WW.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32tasks\RDL208NS.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32tasks\RDL794WW.parquet
C:\Users\nahla\Desktop\threat_hunt_task\003d1fc2-1f7e-4a11-a011-b684a313f9fa\w32tasks\UMI895SB.parquet

In [3]:
import glob

def load_all(folder_name):
    files = glob.glob(dataset_path + f'/{folder_name}/*.parquet')
    dfs = []
    for f in files:
        d = pd.read_parquet(f)
        d['hostname'] = os.path.basename(f).replace('.parquet', '')
        dfs.append(d)
    return pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()

In [4]:
processes = load_all('w32processes')
processes_memory = load_all('w32processes-memorysections')
services = load_all('w32services')
tasks = load_all('w32tasks')
drivers = load_all('w32drivers')
persistence_reg = load_all('w32persistence-registryitems')
persistence_files = load_all('w32persistence-fileitems')
persistence_svc = load_all('w32persistence-serviceitems')
logged_users = load_all('loggedonusers')
user_accounts = load_all('useraccounts')

print(processes.shape, processes_memory.shape, services.shape, tasks.shape)
print(sorted(processes['hostname'].unique()))

(461, 6) (18467, 9) (2183, 14) (604, 14)
['CRW167SL', 'PXA949WW', 'RDL208NS', 'RDL794WW', 'UMI895SB']

In [5]:
domain_users = pd.read_parquet(dataset_path + '/domain_users.parquet')
domain_users

            group        username
0    sanfrancisco         mat.sco
1    sanfrancisco         mat.sco
2    sanfrancisco         mat.sco
3    sanfrancisco         mat.sco
4    sanfrancisco         mat.sco
5    sanfrancisco      flet.lee33
6    sanfrancisco      flet.lee33
7    sanfrancisco  maddi.campbel8
8    sanfrancisco  maddi.campbel8
9    sanfrancisco         ricwood
10   sanfrancisco         ricwood
11   sanfrancisco         ricwood
12   sanfrancisco         ricwood
13  domain admins         mat.sco
14  domain admins   Administrator
15  domain admins          svc_em

In [6]:
print(logged_users.columns.tolist())
logged_users

['domain-user', 'hostname', 'local-user', 'username']

     domain-user  hostname  local-user          username
0          False  CRW167SL        True          Registry
1          False  CRW167SL        True          smss.exe
2          False  CRW167SL        True         lsass.exe
3          False  CRW167SL        True       svchost.exe
4          False  CRW167SL        True      services.exe
..           ...       ...         ...               ...
225        False  UMI895SB        True  vmware-authd.exe
226        False  UMI895SB        True        armsvc.exe
227        False  UMI895SB        True      AcroRd32.exe
228        False  UMI895SB        True        RdrCEF.exe
229        False  UMI895SB        True     Wireshark.exe

[230 rows x 4 columns]

In [7]:
logged_users[logged_users.astype(str).apply(
    lambda row: row.str.contains('admin', case=False, na=False)
).any(axis=1)]

     domain-user  hostname  local-user       username
189         True  RDL794WW       False  Administrator

In [8]:
system_procs = processes[processes['username'].astype(str).str.contains('SYSTEM', case=False, na=False)]
print(system_procs.shape)
system_procs[['hostname','name','path','pid']]

(372, 6)

     hostname         name                 path   pid
0    CRW167SL  svchost.exe  c:\windows\system32  4824
1    CRW167SL  svchost.exe  c:\windows\system32   748
2    CRW167SL  svchost.exe  c:\windows\system32  1084
5    CRW167SL      dwm.exe  C:\Windows\System32  1220
6    CRW167SL   ctfmon.exe  C:\Windows\system32  5140
..        ...          ...                  ...   ...
452  UMI895SB  svchost.exe  C:\Windows\system32  2884
455  UMI895SB  svchost.exe  C:\Windows\system32  1884
456  UMI895SB      Dwm.exe  C:\Windows\system32  5196
458  UMI895SB  conhost.exe  C:\Windows\system32  1928
460  UMI895SB  svchost.exe  C:\Windows\system32  6164

[372 rows x 4 columns]

In [9]:
system_procs[system_procs.astype(str).apply(
    lambda row: row.str.contains(r'Users\\', case=False, na=False)
).any(axis=1)]

Empty DataFrame
Columns: [arguments, hostname, name, path, pid, username]
Index: []

In [10]:
suspicious = processes[processes.astype(str).apply(
    lambda row: row.str.contains('Temp|AppData|ProgramData|WindowsApps', case=False, na=False)
).any(axis=1)]
suspicious[['hostname','name','path','username']]

,hostname,name,path,username
11,CRW167SL,OneDrive.exe,C:\Users\mat.sco\AppData\Local\Microsoft\OneDrive,mat.sco
15,CRW167SL,GitHubDesktop.exe,C:\Users\ricwood\AppData\Local\GitHubDesktop\a...,ricwood
76,CRW167SL,GitHubDesktop.exe,C:\Users\ricwood\AppData\Local\GitHubDesktop\a...,ricwood
95,CRW167SL,SkypeBackgroundHost.exe,C:\Program Files\WindowsApps\Microsoft.SkypeAp...,mat.sco
194,PXA949WW,OneDrive.exe,C:\Users\flet.lee33\AppData\Local\Microsoft\On...,flet.lee33
208,PXA949WW,g2mcomm.exe,C:\Users\maddi.campbel8\AppData\Local\GoToMeet...,maddi.campbel8
215,PXA949WW,g2mstart.exe,C:\Users\maddi.campbel8\AppData\Local\GoToMeet...,maddi.campbel8
242,PXA949WW,SkypeBackgroundHost.exe,C:\Program Files\WindowsApps\Microsoft.SkypeAp...,flet.lee33
265,RDL208NS,GitHubDesktop.exe,C:\Users\dani.robi52\AppData\Local\GitHubDeskt...,dani.robi52
327,RDL208NS,GitHubDesktop.exe,C:\Users\dani.robi52\AppData\Local\GitHubDeskt...,dani.robi52
341,RDL208NS,Calculator.exe,C:\Program Files\WindowsApps\Microsoft.Windows...,ricwood
346,RDL208NS,OneDrive.exe,C:\Users\ricwood\AppData\Local\Microsoft\OneDrive,ricwood
375,RDL794WW,python.exe,C:\Users\ricwood\AppData\Local\Programs\Python...,ricwood
382,RDL794WW,OneDrive.exe,C:\Users\flet.lee33\AppData\Local\Microsoft\On...,flet.lee33
446,UMI895SB,OneDrive.exe,C:\Users\darcieprice\AppData\Local\Microsoft\O...,darcieprice

In [11]:
for h in ['CRW167SL', 'PXA949WW', 'RDL208NS', 'RDL794WW', 'UMI895SB']:
    print(f"--- {h} ---")
    print(processes[processes['hostname'] == h][['name','path','username']].to_string())
    print()

--- CRW167SL ---
                          name                                                                           path             username
0                  svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
1                  svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
2                  svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
3                     mbam.exe                                     C:\Program Files\Malwarebytes\Anti-Malware              mat.sco
4                      cmd.exe                                                    C:\Windows\System32\cmd.exe              mat.sco
5                      dwm.exe                                                            C:\Windows\System32  NT AUTHORITY\SYSTEM
6                   ctfmon.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
7                  svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
8     ApplicationFrameHost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
9          MicrosoftEdgeCP.exe                    C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe              mat.sco
10                SearchUI.exe                  C:\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy  NT AUTHORITY\SYSTEM
11                OneDrive.exe                              C:\Users\mat.sco\AppData\Local\Microsoft\OneDrive              mat.sco
12                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
13                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
14             fontdrvhost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
15           GitHubDesktop.exe                         C:\Users\ricwood\AppData\Local\GitHubDesktop\app-1.4.3              ricwood
16      BtwRSupportService.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
17     ShellExperienceHost.exe                        C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy  NT AUTHORITY\SYSTEM
18                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
19                 svchost.exe                                                            C:\Windows\System32  NT AUTHORITY\SYSTEM
20                  RdrCEF.exe                  C:\Program Files (x86)\Adobe\Acrobat Reader DC\Reader\AcroCEF           elijgonzal
21                    Registry                                                                                 NT AUTHORITY\SYSTEM
22                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
23                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
24                WinLogon.exe                                                            C:\Windows\System32  NT AUTHORITY\SYSTEM
25                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
26                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
27                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
28                git-bash.exe                                                           C:\Program Files\Git           elijgonzal
29                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
30                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
31                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
32                   lsass.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
33                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
34                 svchost.exe                                                            C:\Windows\System32  NT AUTHORITY\SYSTEM
35                 svchost.exe                                                            C:\Windows\System32  NT AUTHORITY\SYSTEM
36                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
37             fontdrvhost.exe                                                            C:\Windows\System32  NT AUTHORITY\SYSTEM
38                      System                                                                                 NT AUTHORITY\SYSTEM
39                    bash.exe                                                   C:\Program Files\Git\usr\bin           elijgonzal
40                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
41                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
42                  tv_w32.exe                                              C:\Program Files (x86)\TeamViewer              mat.sco
43                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
44                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
45                 svchost.exe                                                            C:\Windows\System32  NT AUTHORITY\SYSTEM
46                   sethc.exe                                                  C:\Windows\System32\sethc.exe  NT AUTHORITY\SYSTEM
47                services.exe                                                                                 NT AUTHORITY\SYSTEM
48          Memory Compression                                                                                 NT AUTHORITY\SYSTEM
49                  armsvc.exe                              C:\Program Files (x86)\Common Files\Adobe\ARM\1.0           elijgonzal
50                 svchost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
51              TeamViewer.exe                                              C:\Program Files (x86)\TeamViewer              mat.sco
52                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
53                 svchost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
54                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
55                 svchost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
56                 svchost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
57                   csrss.exe                                                                                 NT AUTHORITY\SYSTEM
58                 svchost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
59                 LockApp.exe                          C:\Windows\SystemApps\Microsoft.LockApp_cw5n1h2txyewy  NT AUTHORITY\SYSTEM
60               taskhostw.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
61                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
62                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
63                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
64                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
65          kitty-0.70.0.6.exe                                                     C:\Users\ricwood\Documents              ricwood
66                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
67                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
68                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
69                  chrome.exe                               C:\Program Files (x86)\Google\Chrome\Application              mat.sco
70                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
71                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
72                 wininit.exe                                                                                 NT AUTHORITY\SYSTEM
73           SearchIndexer.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
74                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
75                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
76           GitHubDesktop.exe                         C:\Users\ricwood\AppData\Local\GitHubDesktop\app-1.4.3              ricwood
77                    smss.exe                                                                                 NT AUTHORITY\SYSTEM
78                  RdrCEF.exe                  C:\Program Files (x86)\Adobe\Acrobat Reader DC\Reader\AcroCEF           elijgonzal
79                 conhost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
80                 jusched.exe                           C:\Program Files (x86)\Common Files\Java\Java Update  NT AUTHORITY\SYSTEM
81         SettingSyncHost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
82                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
83                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
84                  mintty.exe                                                   C:\Program Files\Git\usr\bin           elijgonzal
85                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
86                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
87                AcroRd32.exe                          C:\Program Files (x86)\Adobe\Acrobat Reader DC\Reader           elijgonzal
88                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
89                 svchost.exe                                                                                 NT AUTHORITY\SYSTEM
90        SearchFilterHost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
91              SgrmBroker.exe                                                                                 NT AUTHORITY\SYSTEM
92                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
93                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
94                AcroRd32.exe                          C:\Program Files (x86)\Adobe\Acrobat Reader DC\Reader           elijgonzal
95     SkypeBackgroundHost.exe  C:\Program Files\WindowsApps\Microsoft.SkypeApp_14.33.41.0_x64__kzf8qxf38zg5c              mat.sco
96                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
97                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
98                 DllHost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
99      TeamViewer_Service.exe                                              C:\Program Files (x86)\TeamViewer              mat.sco
100                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
101                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
102                 sihost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
103                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
104                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
105                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
106          RuntimeBroker.exe                                                            C:\Windows\System32  NT AUTHORITY\SYSTEM
107                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
108                svchost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
109                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
110                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
111                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
112                cscript.exe                                                C:\Windows\System32\cscript.exe  NT AUTHORITY\SYSTEM
113                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
114                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
115                 NisSrv.exe                                                                                 NT AUTHORITY\SYSTEM
116                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
117                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
118                svchost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
119               Explorer.EXE                                                                     C:\Windows  NT AUTHORITY\SYSTEM
120            mbamservice.exe                                     C:\Program Files\Malwarebytes\Anti-Malware              mat.sco
121                spoolsv.exe                                                            C:\Windows\System32  NT AUTHORITY\SYSTEM
122  SecurityHealthService.exe                                                                                 NT AUTHORITY\SYSTEM
123                MsMpEng.exe                                                                                 NT AUTHORITY\SYSTEM
124                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM

--- PXA949WW ---
                          name                                                                           path             username
125                svchost.exe                                                                                 NT AUTHORITY\SYSTEM
126                DllHost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
127            fontdrvhost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
128                 NisSrv.exe                                                                                 NT AUTHORITY\SYSTEM
129                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
130                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
131                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
132                MsMpEng.exe                                                                                 NT AUTHORITY\SYSTEM
133                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
134                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
135                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
136            mbamservice.exe                                     C:\Program Files\Malwarebytes\Anti-Malware       maddi.campbel8
137        MicrosoftEdgeCP.exe                    C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe       maddi.campbel8
138     TeamViewer_Service.exe                                              C:\Program Files (x86)\TeamViewer           flet.lee33
139                jusched.exe                           C:\Program Files (x86)\Common Files\Java\Java Update  NT AUTHORITY\SYSTEM
140          RuntimeBroker.exe                                                            C:\Windows\System32  NT AUTHORITY\SYSTEM
141         Memory Compression                                                                                 NT AUTHORITY\SYSTEM
142                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
143                 sihost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
144                    dwm.exe                                                            C:\Windows\System32  NT AUTHORITY\SYSTEM
145                conhost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
146  SecurityHealthService.exe                                                                                 NT AUTHORITY\SYSTEM
147                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
148         kitty-0.70.0.6.exe                                                  C:\Users\flet.lee33\Documents           flet.lee33
149                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM

In [12]:
logged_users

     domain-user  hostname  local-user          username
0          False  CRW167SL        True          Registry
1          False  CRW167SL        True          smss.exe
2          False  CRW167SL        True         lsass.exe
3          False  CRW167SL        True       svchost.exe
4          False  CRW167SL        True      services.exe
..           ...       ...         ...               ...
225        False  UMI895SB        True  vmware-authd.exe
226        False  UMI895SB        True        armsvc.exe
227        False  UMI895SB        True      AcroRd32.exe
228        False  UMI895SB        True        RdrCEF.exe
229        False  UMI895SB        True     Wireshark.exe

[230 rows x 4 columns]

In [13]:
user_accounts

,domain-admin,domain-user,hostname,local-admin,local-user,username
0,False,True,CRW167SL,False,False,ricwood
1,False,True,CRW167SL,False,False,mat.sco
2,False,False,CRW167SL,False,True,elijgonzal
3,False,False,CRW167SL,True,True,zBMIahqYKPEfTT
4,False,True,PXA949WW,False,False,flet.lee33
5,False,True,PXA949WW,True,False,ricwood
6,False,True,PXA949WW,False,False,maddi.campbel8
7,True,True,PXA949WW,False,False,Administrator
8,False,False,PXA949WW,True,True,dEkSarQLRvDfhPA
9,False,True,RDL208NS,True,False,mat.sco
10,False,True,RDL208NS,True,False,ricwood
11,False,False,RDL208NS,True,True,evebail
12,False,False,RDL208NS,True,True,dani.robi52
13,False,False,RDL208NS,True,True,amber.hill
14,False,True,RDL794WW,True,False,ricwood
15,False,True,RDL794WW,False,False,maddi.campbel8
16,True,True,RDL794WW,False,False,Administrator
17,False,True,RDL794WW,True,False,flet.lee33
18,False,True,UMI895SB,False,False,ricwood
19,True,True,UMI895SB,False,False,mat.sco
20,False,False,UMI895SB,False,True,darcieprice

In [14]:
print(processes['name'].value_counts())

name
svchost.exe        235
fontdrvhost.exe      6
RdrCEF.exe           6
AcroRd32.exe         6
mbam.exe             5
                  ...
soffice.bin          1
lsm.exe              1
taskhost.exe         1
soffice.exe          1
Dwm.exe              1
Name: count, Length: 80, dtype: int64

In [15]:
tasks['hostname'].value_counts()

hostname
CRW167SL    145
PXA949WW    145
RDL208NS    144
RDL794WW    126
UMI895SB     44
Name: count, dtype: int64

In [16]:
for h in ['CRW167SL', 'PXA949WW', 'RDL208NS', 'RDL794WW', 'UMI895SB']:
    t = tasks[tasks['hostname'] == h]
    print(f"--- {h}: {len(t)} tasks ---")

--- CRW167SL: 145 tasks ---
--- PXA949WW: 145 tasks ---
--- RDL208NS: 144 tasks ---
--- RDL794WW: 126 tasks ---
--- UMI895SB: 44 tasks ---

In [17]:
user_accounts[user_accounts['username'].str.contains('zBMI|dEkS', case=False, na=False)]

,domain-admin,domain-user,hostname,local-admin,local-user,username
3,False,False,CRW167SL,True,True,zBMIahqYKPEfTT
8,False,False,PXA949WW,True,True,dEkSarQLRvDfhPA

In [18]:
for h in ['CRW167SL', 'PXA949WW']:
    print(f"=== {h} — Registry Persistence ===")
    print(persistence_reg[persistence_reg['hostname'] == h].to_string())
    print(f"=== {h} — File Persistence ===")
    print(persistence_files[persistence_files['hostname'] == h].to_string())

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

   drive fileextension                         filename                                                          filepath                                                                          fullpath  hostname                     username
12     c           exe                  mbamservice.exe                           program files\malwarebytes\anti-malware                        c:\program files\malwarebytes\anti-malware\mbamservice.exe  PXA949WW       BUILTIN\Administrators
13     c           dll  onedrivesettingsyncprovider.dll                                                  Windows\System32                               c:\Windows\System32\onedrivesettingsyncprovider.dll  PXA949WW  NT SERVICE\TrustedInstaller
14     c           exe                onedrivesetup.exe                                                  Windows\SysWOW64                                             c:\Windows\SysWOW64\onedrivesetup.exe  PXA949WW  NT SERVICE\TrustedInstaller
15     c           exe                     OneDrive.exe                      Users\$user\AppData\Local\microsoft\OneDrive                      c:\Users\$user\AppData\Local\microsoft\OneDrive\OneDrive.exe  PXA949WW                $domain\$user
16     c           exe                     sqlservr.exe  program files\microsoft sql server\mssql14.sqlexpress\MSSQL\Binn  c:\program files\microsoft sql server\mssql14.sqlexpress\MSSQL\Binn\sqlservr.exe  PXA949WW          NT AUTHORITY\SYSTEM
17     c           dll                     PhotoAcq.dll                                program files\windows photo viewer                                c:\program files\windows photo viewer\PhotoAcq.dll  PXA949WW  NT SERVICE\TrustedInstaller
18     c           EXE                     SQLAGENT.EXE  program files\microsoft sql server\mssql14.sqlexpress\MSSQL\Binn  c:\program files\microsoft sql server\mssql14.sqlexpress\MSSQL\Binn\SQLAGENT.EXE  PXA949WW          NT AUTHORITY\SYSTEM
19     c           dll            accessiblemarshal.dll                           program files (x86)\mozilla thunderbird                  c:\program files (x86)\mozilla thunderbird\accessiblemarshal.dll  PXA949WW       BUILTIN\Administrators
20     c           dll              mapiproxy_inuse.dll                           program files (x86)\mozilla thunderbird                    c:\program files (x86)\mozilla thunderbird\mapiproxy_inuse.dll  PXA949WW       BUILTIN\Administrators

In [19]:
for h in ['CRW167SL', 'PXA949WW']:
    print(f"=== {h} — All Processes ===")
    print(processes[processes['hostname'] == h][['name','path','username']].to_string())

=== CRW167SL — All Processes ===
                          name                                                                           path             username
0                  svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
1                  svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
2                  svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
3                     mbam.exe                                     C:\Program Files\Malwarebytes\Anti-Malware              mat.sco
4                      cmd.exe                                                    C:\Windows\System32\cmd.exe              mat.sco
5                      dwm.exe                                                            C:\Windows\System32  NT AUTHORITY\SYSTEM
6                   ctfmon.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
7                  svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
8     ApplicationFrameHost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
9          MicrosoftEdgeCP.exe                    C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe              mat.sco
10                SearchUI.exe                  C:\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy  NT AUTHORITY\SYSTEM
11                OneDrive.exe                              C:\Users\mat.sco\AppData\Local\Microsoft\OneDrive              mat.sco
12                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
13                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
14             fontdrvhost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
15           GitHubDesktop.exe                         C:\Users\ricwood\AppData\Local\GitHubDesktop\app-1.4.3              ricwood
16      BtwRSupportService.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
17     ShellExperienceHost.exe                        C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy  NT AUTHORITY\SYSTEM
18                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
19                 svchost.exe                                                            C:\Windows\System32  NT AUTHORITY\SYSTEM
20                  RdrCEF.exe                  C:\Program Files (x86)\Adobe\Acrobat Reader DC\Reader\AcroCEF           elijgonzal
21                    Registry                                                                                 NT AUTHORITY\SYSTEM
22                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
23                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
24                WinLogon.exe                                                            C:\Windows\System32  NT AUTHORITY\SYSTEM
25                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
26                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
27                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
28                git-bash.exe                                                           C:\Program Files\Git           elijgonzal
29                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
30                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
31                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
32                   lsass.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
33                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
34                 svchost.exe                                                            C:\Windows\System32  NT AUTHORITY\SYSTEM
35                 svchost.exe                                                            C:\Windows\System32  NT AUTHORITY\SYSTEM
36                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
37             fontdrvhost.exe                                                            C:\Windows\System32  NT AUTHORITY\SYSTEM
38                      System                                                                                 NT AUTHORITY\SYSTEM
39                    bash.exe                                                   C:\Program Files\Git\usr\bin           elijgonzal
40                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
41                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
42                  tv_w32.exe                                              C:\Program Files (x86)\TeamViewer              mat.sco
43                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
44                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
45                 svchost.exe                                                            C:\Windows\System32  NT AUTHORITY\SYSTEM
46                   sethc.exe                                                  C:\Windows\System32\sethc.exe  NT AUTHORITY\SYSTEM
47                services.exe                                                                                 NT AUTHORITY\SYSTEM
48          Memory Compression                                                                                 NT AUTHORITY\SYSTEM
49                  armsvc.exe                              C:\Program Files (x86)\Common Files\Adobe\ARM\1.0           elijgonzal
50                 svchost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
51              TeamViewer.exe                                              C:\Program Files (x86)\TeamViewer              mat.sco
52                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
53                 svchost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
54                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
55                 svchost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
56                 svchost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
57                   csrss.exe                                                                                 NT AUTHORITY\SYSTEM
58                 svchost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
59                 LockApp.exe                          C:\Windows\SystemApps\Microsoft.LockApp_cw5n1h2txyewy  NT AUTHORITY\SYSTEM
60               taskhostw.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
61                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
62                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
63                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
64                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
65          kitty-0.70.0.6.exe                                                     C:\Users\ricwood\Documents              ricwood
66                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
67                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
68                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
69                  chrome.exe                               C:\Program Files (x86)\Google\Chrome\Application              mat.sco
70                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
71                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
72                 wininit.exe                                                                                 NT AUTHORITY\SYSTEM
73           SearchIndexer.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
74                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
75                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
76           GitHubDesktop.exe                         C:\Users\ricwood\AppData\Local\GitHubDesktop\app-1.4.3              ricwood
77                    smss.exe                                                                                 NT AUTHORITY\SYSTEM
78                  RdrCEF.exe                  C:\Program Files (x86)\Adobe\Acrobat Reader DC\Reader\AcroCEF           elijgonzal
79                 conhost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
80                 jusched.exe                           C:\Program Files (x86)\Common Files\Java\Java Update  NT AUTHORITY\SYSTEM
81         SettingSyncHost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
82                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
83                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
84                  mintty.exe                                                   C:\Program Files\Git\usr\bin           elijgonzal
85                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
86                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
87                AcroRd32.exe                          C:\Program Files (x86)\Adobe\Acrobat Reader DC\Reader           elijgonzal
88                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
89                 svchost.exe                                                                                 NT AUTHORITY\SYSTEM
90        SearchFilterHost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
91              SgrmBroker.exe                                                                                 NT AUTHORITY\SYSTEM
92                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
93                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
94                AcroRd32.exe                          C:\Program Files (x86)\Adobe\Acrobat Reader DC\Reader           elijgonzal
95     SkypeBackgroundHost.exe  C:\Program Files\WindowsApps\Microsoft.SkypeApp_14.33.41.0_x64__kzf8qxf38zg5c              mat.sco
96                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
97                 svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
98                 DllHost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
99      TeamViewer_Service.exe                                              C:\Program Files (x86)\TeamViewer              mat.sco
100                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
101                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
102                 sihost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
103                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
104                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
105                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
106          RuntimeBroker.exe                                                            C:\Windows\System32  NT AUTHORITY\SYSTEM
107                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
108                svchost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
109                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
110                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
111                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
112                cscript.exe                                                C:\Windows\System32\cscript.exe  NT AUTHORITY\SYSTEM
113                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
114                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
115                 NisSrv.exe                                                                                 NT AUTHORITY\SYSTEM
116                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
117                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
118                svchost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
119               Explorer.EXE                                                                     C:\Windows  NT AUTHORITY\SYSTEM
120            mbamservice.exe                                     C:\Program Files\Malwarebytes\Anti-Malware              mat.sco
121                spoolsv.exe                                                            C:\Windows\System32  NT AUTHORITY\SYSTEM
122  SecurityHealthService.exe                                                                                 NT AUTHORITY\SYSTEM
123                MsMpEng.exe                                                                                 NT AUTHORITY\SYSTEM
124                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
=== PXA949WW — All Processes ===
                          name                                                                           path             username
125                svchost.exe                                                                                 NT AUTHORITY\SYSTEM
126                DllHost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
127            fontdrvhost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
128                 NisSrv.exe                                                                                 NT AUTHORITY\SYSTEM
129                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
130                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
131                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
132                MsMpEng.exe                                                                                 NT AUTHORITY\SYSTEM
133                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
134                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
135                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
136            mbamservice.exe                                     C:\Program Files\Malwarebytes\Anti-Malware       maddi.campbel8
137        MicrosoftEdgeCP.exe                    C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe       maddi.campbel8
138     TeamViewer_Service.exe                                              C:\Program Files (x86)\TeamViewer           flet.lee33
139                jusched.exe                           C:\Program Files (x86)\Common Files\Java\Java Update  NT AUTHORITY\SYSTEM
140          RuntimeBroker.exe                                                            C:\Windows\System32  NT AUTHORITY\SYSTEM
141         Memory Compression                                                                                 NT AUTHORITY\SYSTEM
142                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
143                 sihost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
144                    dwm.exe                                                            C:\Windows\System32  NT AUTHORITY\SYSTEM
145                conhost.exe                                                            C:\Windows\system32  NT AUTHORITY\SYSTEM
146  SecurityHealthService.exe                                                                                 NT AUTHORITY\SYSTEM
147                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM
148         kitty-0.70.0.6.exe                                                  C:\Users\flet.lee33\Documents           flet.lee33
149                svchost.exe                                                            c:\windows\system32  NT AUTHORITY\SYSTEM

In [20]:
for h in ['CRW167SL', 'PXA949WW']:
    print(f"=== {h} — Services ===")
    print(services[services['hostname'] == h].to_string())

=== CRW167SL — Services ===
                                                                                                    arguments                                                                                                                                                                                                                                                                                                                                                      description                                                              descriptivename  hostname                               md5                          name                                                                                                     path                            pathcertificateissuer                              pathcertificatesubject                            pathsignaturedescription pathsignatureexists pathsignatureverified                                               servicedll                                                   type
0                                                               C:\Windows\system32\svchost.exe -k netsvcs -p                                                                                                                                                                                                                                                                                                                 This service manages connected Xbox Accessories.                                            Xbox Accessory Management Service  CRW167SL  77ff6ee7b791cf3dbbf4ffd19e847fe4                    XboxGipSvc                                                                          C:\Windows\System32\svchost.exe            Microsoft Windows Production PCA 2011                                   Microsoft Windows  The file is signed and the signature was verified.                true                  true                       C:\Windows\System32\XboxGipSvc.dll                            SERVICE_WIN32_SHARE_PROCESS
1                                                            C:\Windows\system32\svchost.exe -k DcomLaunch -p                                                                                                                                                                                                Enables a computer to recognize and adapt to hardware changes with little or no user input. Stopping or disabling this service will result in system instability.                                                       Device Install Service  CRW167SL  77ff6ee7b791cf3dbbf4ffd19e847fe4                 DeviceInstall                                                                          C:\Windows\System32\svchost.exe            Microsoft Windows Production PCA 2011                                   Microsoft Windows  The file is signed and the signature was verified.                true                  true                         C:\Windows\System32\umpnpmgr.dll  SERVICE_WIN32_OWN_PROCESS SERVICE_WIN32_SHARE_PROCESS
2                                                                     \SystemRoot\System32\drivers\bcmfn2.sys                                                                                                                                                                                                                                                                                                                                                                                                                                bcmfn2 Service  CRW167SL  430161af3a3eecc491709ba556477a15                        bcmfn2                                                                   C:\Windows\System32\drivers\bcmfn2.sys            Microsoft Windows Production PCA 2011                                   Microsoft Windows  The file is signed and the signature was verified.                true                  true                                                                                           SERVICE_KERNEL_DRIVER
3                                                                                system32\drivers\ndisuio.sys                                                                                                                                                                                                                                                                                                                                                                                                                    NDIS Usermode I/O Protocol  CRW167SL  3bf20d164c7229bdd6846665d703ed7a                       Ndisuio                                                                  C:\Windows\System32\drivers\ndisuio.sys            Microsoft Windows Production PCA 2011                                   Microsoft Windows  The file is signed and the signature was verified.                true                  true                                                                                           SERVICE_KERNEL_DRIVER
4                                                             \SystemRoot\system32\drivers\UevAgentDriver.sys                                                                                                                                                                                                                                                                                                                      User Experience Virtualization Agent Driver                                                               UevAgentDriver  CRW167SL  ba3aab9fc2660454844a909e7580392d                UevAgentDriver                                                           C:\Windows\System32\drivers\UevAgentDriver.sys            Microsoft Windows Production PCA 2011                                   Microsoft Windows  The file is signed and the signature was verified.                true                  true                                                                                      SERVICE_FILE_SYSTEM_DRIVER
5                                                                      \SystemRoot\System32\drivers\vmgid.sys                                                                                                                                                                                                                                                                                                                                                                                                 Microsoft Hyper-V Guest Infrastructure Driver  CRW167SL  dbfcaa953b5c7ecbad2bcf6cf65abe1e                         vmgid                                                                    C:\Windows\System32\drivers\vmgid.sys            Microsoft Windows Production PCA 2011                                   Microsoft Windows  The file is signed and the signature was verified.                true                  true                                                                                           SERVICE_KERNEL_DRIVER
6                                          C:\Windows\System32\svchost.exe -k LocalSystemNetworkRestricted -p                                                                                                                                                                                                                                                                                   Provides enabling services for storage settings and external storage expansion                                                              Storage Service  CRW167SL  77ff6ee7b791cf3dbbf4ffd19e847fe4                       StorSvc                                                                          C:\Windows\System32\svchost.exe            Microsoft Windows Production PCA 2011                                   Microsoft Windows  The file is signed and the signature was verified.                true                  true                          C:\Windows\System32\StorSvc.dll  SERVICE_WIN32_OWN_PROCESS SERVICE_WIN32_SHARE_PROCESS
7                                                                    \SystemRoot\System32\drivers\UsbHub3.sys                                                                                                                                                                                                                                                                                                                                                                                                                                SuperSpeed Hub  CRW167SL  4f1cbee26f895dd87c95a793bda9d3ce                       USBHUB3                                                                  C:\Windows\System32\drivers\USBHUB3.SYS            Microsoft Windows Production PCA 2011                                   Microsoft Windows  The file is signed and the signature was verified.                true                  true                                                                                           SERVICE_KERNEL_DRIVER
8                                                                               system32\drivers\tsusbflt.sys                                                                                                                                                                                                                                                                                                                       Remote Desktop USB Hub Class Filter Driver                                   Remote Desktop USB Hub Class Filter Driver  CRW167SL  b85131b18ab1833f3df0f4fe92dbb54b                      TsUsbFlt                                                                 C:\Windows\System32\drivers\TsUsbFlt.sys            Microsoft Windows Production PCA 2011                                   Microsoft Windows  The file is signed and the signature was verified.                true                  true                                                                                           SERVICE_KERNEL_DRIVER
9                                                                    \SystemRoot\System32\drivers\monitor.sys                                                                                                                                                                                                                                                                                                                                                                                               Microsoft Monitor Class Function Driver Service  CRW167SL  7a07c43511323117b6a8dbd570a12635                       monitor                                                                  C:\Windows\System32\drivers\monitor.sys            Microsoft Windows Production PCA 2011                                   Microsoft Windows  The file is signed and the signature was verified.                true                  true                                                                                           SERVICE_KERNEL_DRIVER
10                                                           C:\Windows\system32\svchost.exe -k DcomLaunch -p                                                                                                                                                                                                                                     Core Windows Service that manages local user sessions. Stopping or disabling this service will result in system instability.                                                        Local Session Manager  CRW167SL  77ff6ee7b791cf3dbbf4ffd19e847fe4                           LSM                                                                          C:\Windows\System32\svchost.exe            Microsoft Windows Production PCA 2011                                   Microsoft Windows  The file is signed and the signature was verified.                true                  true                              C:\Windows\System32\lsm.dll  SERVICE_WIN32_OWN_PROCESS SERVICE_WIN32_SHARE_PROCESS
11                                           C:\Windows\System32\svchost.exe -k LocalServiceNetworkRestricted                                                                                                                                                                                                                                                                                                                       Radio Management and Airplane Mode Service                                                     Radio Management Service  CRW167SL  77ff6ee7b791cf3dbbf4ffd19e847fe4                         RmSvc                                                                          C:\Windows\System32\svchost.exe            Microsoft Windows Production PCA 2011                                   Microsoft Windows  The file is signed and the signature was verified.                true                  true                            C:\Windows\System32\RMapi.dll                            SERVICE_WIN32_SHARE_PROCESS
12                                                                                system32\drivers\WudfPf.sys                                                                                                                                                                                                                                                                                                                                                                                                   User Mode Driver Frameworks Platform Driver  CRW167SL  459a881b6ba721115e6767d63b42d86b                        WudfPf                                                                   C:\Windows\System32\drivers\WUDFPf.sys            Microsoft Windows Production PCA 2011                                   Microsoft Windows  The file is signed and the signature was verified.                true                  true                                                                                           SERVICE_KERNEL_DRIVER
13                                                                    \SystemRoot\System32\drivers\bthpan.sys                                                                                                                                                                                                                                                                                                                         Bluetooth Device (Personal Area Network)                                     Bluetooth Device (Personal Area Network)  CRW167SL  25f62d85a569c4cdab167f417e776b59                        BthPan                                                                   C:\Windows\System32\drivers\bthpan.sys            Microsoft Windows Production PCA 2011                                   Microsoft Windows  The file is signed and the signature was verified.                true                  true                                                                                           SERVICE_KERNEL_DRIVER
14                                                                  \SystemRoot\System32\drivers\mlx4_bus.sys                                                                                                                                                                                                                                                                                                                                                                                                              Mellanox ConnectX Bus Enumerator  CRW167SL  0d118a0fc14c6bfd41f838f31ff3b568                      mlx4_bus                                                                 C:\Windows\System32\drivers\mlx4_bus.sys            Microsoft Windows Production PCA 2011                                   Microsoft Windows  The file is signed and the signature was verified.                true                  true                                                                                           SERVICE_KERNEL_DRIVER
15                                         C:\Windows\system32\svchost.exe -k LocalSystemNetworkRestricted -p                                                                                                                                                                                                                                                                                    Protects user files from accidental loss by copying them to a backup location                                                         File History Service  CRW167SL  77ff6ee7b791cf3dbbf4ffd19e847fe4                         fhsvc                                                                          C:\Windows\System32\svchost.exe            Microsoft Windows Production PCA 2011                                   Microsoft Windows  The file is signed and the signature was verified.                true                  true                            C:\Windows\System32\fhsvc.dll                            SERVICE_WIN32_SHARE_PROCESS
16                                                                  \SystemRoot\System32\drivers\vstxraid.sys                                                                                                                                                                                                                                                                                                                                                                                              VIA StorX Storage RAID Controller Windows Driver  CRW167SL  022cde1926756fa8045564639a63ac2e                      VSTXRAID                                                                 C:\Windows\System32\drivers\VSTXRAID.SYS            Microsoft Windows Production PCA 2011                                   Microsoft Windows  The file is signed and the signature was verified.                true                  true                                                                                           SERVICE_KERNEL_DRIVER
17                                                                                  system32\DRIVERS\cdfs.sys                                                                                                                                                                                                                                                                                               ISO9660/Joliet File System Reader for CD/DVDs. (Core) (All pieces)                                                    CD/DVD File System Reader  CRW167SL  e020ead089d402936500d5ab5613dcd3                          cdfs                                                                     C:\Windows\System32\drivers\cdfs.sys            Microsoft Windows Production PCA 2011                                   Microsoft Windows  The file is signed and the signature was verified.                true                  true                                                                                      SERVICE_FILE_SYSTEM_DRIVER

In [21]:
processes[processes['username'].astype(str).str.contains('svc_em', case=False, na=False)]

Empty DataFrame
Columns: [arguments, hostname, name, path, pid, username]
Index: []

In [22]:
services[services.astype(str).apply(lambda row: row.str.contains('svc_em', case=False, na=False)).any(axis=1)]

Empty DataFrame
Columns: [arguments, description, descriptivename, hostname, md5, name, path, pathcertificateissuer, pathcertificatesubject, pathsignaturedescription, pathsignatureexists, pathsignatureverified, servicedll, type]
Index: []

In [23]:
persistence_files[persistence_files.astype(str).apply(lambda row: row.str.contains('Public', case=False, na=False)).any(axis=1)]

,drive,fileextension,filename,filepath,fullpath,hostname,username
1578,c,dll,mbaeapipublic.dll,Windows\SysWOW64,c:\Windows\SysWOW64\mbaeapipublic.dll,RDL794WW,NT AUTHORITY\SYSTEM
2150,c,dll,mbaeapipublic.dll,Windows\System32,c:\Windows\System32\mbaeapipublic.dll,RDL794WW,NT AUTHORITY\SYSTEM

In [24]:
logged_users[logged_users['username'].isin(['zBMIahqYKPEfTT', 'dEkSarQLRvDfhPA'])]

Empty DataFrame
Columns: [domain-user, hostname, local-user, username]
Index: []

In [30]:
## Findings Summary

###**Two compromised machines identified: CRW167SL and PXA949WW**

### CRW167SL

#### **Randomly-generated local admin account**: A local account named `zBMIahqYKPEfTT` was found with `local-admin = True`. This naming pattern (random alphanumeric string) is inconsistent with the organization's normal username convention (e.g. `firstname.lastname`) and is a strong indicator of an attacker-created backdoor account.

#### **Malicious service masquerading (hidinterrupt)**: A service named `hidinterrupt` was found pointing to `C:\Public\run.vbs`. On a comparison host (PXA949WW), the legitimate service with the same name (`hidinterrupt`) correctly points to `C:\Windows\System32\drivers\hidinterrupt.sys`, a genuine Windows kernel driver. Replacing a trusted system service's target with a `.vbs` script in a non-standard, world-writable location (`C:\Public`) is a classic service masquerading / persistence technique used to blend malicious code in with legitimate-looking system services.

### PXA949WW

#### **Randomly-generated local admin account**: A local account named `dEkSarQLRvDfhPA` was found with `local-admin = True`, following the same suspicious random-string naming pattern observed on CRW167SL.

### Conclusion

#### Both `CRW167SL` and `PXA949WW` show independent, host-specific indicators of compromise not present on the other three hosts in the dataset (`RDL208NS`, `RDL794WW`, `UMI895SB`). The presence of randomly-named local administrator accounts on both machines, combined with a confirmed malicious service masquerading as a legitimate Windows driver on `CRW167SL`, provides strong evidence that these two hosts were compromised — most likely through the creation of hidden backdoor accounts and a service-based persistence mechanism.

#### (See the accompanying report for the Executive Summary, IOC explanations in plain language, recommendations, limitations, and assumptions.)*